AspMvcUserAdministration/AspMvcUserAdministration/Controllers/FileUpploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AspMvcUserAdministration.Controllers
{
    [Authorize(Roles = "Upploader, Administrator")]
    public class FileUpploadController : Controller
    {
        // GET: FileUppload
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveAndPersist(IEnumerable<HttpPostedFileBase> upload)
        {
            StringBuilder messageBuilder = new StringBuilder();

            if (upload != null)
            {
                
                foreach (var file in upload)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var physicalPath = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                    if (!System.IO.File.Exists(physicalPath))
                    {
                        file.SaveAs(physicalPath);
                    }
                    else 
                    {
                        messageBuilder.Append("File \"" + file.FileName + "\" allready exists!<br />");
                    }
                }
            }

            if (messageBuilder.Length > 0)
            {
                return Content(messageBuilder.ToString());
            }
            else 
            {
                return Content("");
            }
        }
    }
}

AspMvcUserAdministration/AspMvcUserAdministration/Controllers/UserAdministrationController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AspMvcUserAdministration.Data;
using AspMvcUserAdministration.Models;
using AspMvcUserAdministration.Models.ViewModels;
using Kendo.Mvc.UI;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Kendo.Mvc.Extensions;
using AspMvcUserAdministration.Helpers;

namespace AspMvcUserAdministration.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserAdministrationController : Controller
    {
        private IUowData db;
        private IList<IdentityRole> roles;
        public UserAdministrationController(IUowData db)
        {
            this.db = db;
            this.roles = db.Roles.All().ToList();
        }

        // GET: UserAdministration/Home
        public ActionResult Index()
        {
            ViewData["Roles"] = roles;
            return View();
        }

        public JsonResult ReadAllUsers([DataSourceRequest]DataSourceRequest request)
        {
            var users = db.Users.All().Select(AccountViewModel.ToAccountViewModel);
            return Json(users.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetRolesByUser(string userId, [DataSourceRequest] DataSourceRequest request)
        {
            var userRoles = (db.Users.GetById(userId)).ToAccountViewModel().Roles;
            return Json(userRoles.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UpdateUser(AccountViewModel userAccount,[DataSourceRequest] DataSourceRequest request)
        {
            try
            {

                var persistentUser = db.Users.GetById(userAccount.Id);
                persistentUser.CopyPropFromAccountViewModel(userAccount, roles);
                db.Users.Update(persistentUser);
                db.SaveChanges();
                return Json(new[] { persistentUser.ToAccountViewModel() }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.GetType().ToString(), ex.Message);
                return Json(new[] { userAccount }.ToDataSourceResult(request, ModelState));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> _AddNewUser(RegisterViewModel model, string urlToRedirect)
        {
            if (ModelState.IsValid)
            {
                var UserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                var user = new ApplicationUser() { UserName = model.UserName, Email = model.Email };
                IdentityResult result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return Redirect(urlToRedirect);
                }
                else
                {
                    AddErrors(result);
                }
            }
            ViewBag.Visible = true;
            return View(model);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        [HttpPost]
        public ActionResult DeleteUser([DataSourceRequest]DataSourceRequest request, AccountViewModel user)
        {

                if (user != null && ModelState.IsValid)
                {
                        if (user.Id == User.Identity.GetUserId())
                        {
                            ModelState.AddModelError("", "You cannot delete current user.");
                        }
                        else
                        {
                            db.Users.Delete(user.Id);
                            db.SaveChanges();
                        }
                }

                var users = db.Users.All().Select(AccountViewModel.ToAccountViewModel).ToList();

                return Json(users.ToDataSourceResult(request, ModelState));
        }
    }
}

AspMvcUserAdministration/AspMvcUserAdministration/Views/Shared/_AddNewUser.cshtml
@model AspMvcUserAdministration.Models.RegisterViewModel
@(Html.Kendo().Window().Name("AddNewUser")
    .Title("Add New User")
    .Visible(ViewBag.Visible != null ? (bool)ViewBag.Visible : false)
    .Modal(true)
    .Draggable(true)
    .Width(500)
        .Content(@<text>
        <form  action="/UserAdministration/_AddNewUser" method="post">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })
            @Html.Hidden("urlToRedirect", "Index")
            <div class="form-group">
                <div class="col-md-2">
                    @Html.LabelFor(m => m.UserName, new { @class = "editor-label" })
                </div>
                @Html.TextBoxFor(m => m.UserName, new { @class = "editor-field" })
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    @Html.LabelFor(m => m.Email, new { @class = "editor-label" })
                </div>
                @Html.TextBoxFor(m => m.Email, new { @class = "editor-field" })
            </div>
            <div class="form-group">

                <div class="col-md-2">
                    @Html.LabelFor(m => m.Password, new { @class = "editor-label" })
                </div>
                @Html.PasswordFor(m => m.Password, new { @class = "editor-field" })
            </div>

            <div class="form-group">
                <div class="col-md-2">
                    @Html.LabelFor(m => m.ConfirmPassword, new { @class = "editor-label" })
                </div>
                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "editor-field" })
            </div>
            <div class="k-edit-buttons k-state-default">
                <input type="submit" name="CreateUser" value="Create User" class="k-button k-button-icontext k-grid-edit" />
                <input type="button" value="Cansel" id="cancel" onclick="javascript: $('#AddNewUser').data('kendoWindow').close();" class="k-button k-button-icontext k-grid-edit" />
            </div>
        </form>
        </text>))

AspMvcUserAdministration/AspMvcUserAdministration/Views/Shared/_FileUppload.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated && (User.IsInRole("Administrator") || User.IsInRole("Upploader")))
{
        <li>@Html.ActionLink("Uppload File", "Index", "FileUppload")</li>
}

AspMvcUserAdministration/AspMvcUserAdministration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css/styles")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/kendo/styles")
    @Scripts.Render("~/bundles/kendo")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" ", "Index", "Home", null, new { @class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @Html.Partial("_FileUppload")
                    @Html.Partial("_UserAdministration")
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - File Uppload System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AspMvcUserAdministration/AspMvcUserAdministration/Views/Shared/_ResetPassword.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav navbar-right">
        <li>
            @Html.ActionLink("Change Password", "ChangePassword", "Account");
        </li>
    </ul>
}

AspMvcUserAdministration/AspMvcUserAdministration/Views/Shared/_UserAdministration.cshtml
@if (Request.IsAuthenticated && User.IsInRole("Administrator"))
{
    <li>@Html.ActionLink("User Administration", "Index", "UserAdministration")</li>
}