09.ASP.NET MVC/04.Kendo UI ASP.NET MVC Wrappers/Test/KendoUIWrappers/KendoUIWrappersTest/Controllers/WorldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Countries.Data.Models;
using Countries.Data.ViewModels;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace KendoUIWrappersTest.Controllers
{
    public class WorldController : Controller
    {
        public WorldController()
        {
            this.Data = new WorldContext();
        }

        public WorldContext Data { get; set; }

        // GET: World
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ReadCountries([DataSourceRequest]DataSourceRequest request) 
        {
            var countires = this.Data.Countries.Include("Cities").Include("CountryLanguages").Select(CountryViewModel.ToCountryViewModel);

            return Json(countires.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
    }
}

09.ASP.NET MVC/04.Kendo UI ASP.NET MVC Wrappers/Test/KendoUIWrappers/KendoUIWrappersTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/kendo")
    @Scripts.Render("~/bundles/kendo")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">World<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Countries Details", "Index", "World")
                            </li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>